name: Build and Push Docker Image

on:
  push:
    branches: [ "main" ]  # Пайплайн сработает, когда сделаем push в main

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and push
      uses: docker/build-push-action@v4
      with:
        # Указываем путь к Lab2
        context: ./lab2
        push: true
        tags: emiliabulgakova/my-flask-app:latest

    - name: Deploy step
      run: echo "The image has been successfully pushed and 'deployed'!"